[package]
name = "mcl_kzg_bench"
version = "0.1.0"
edition = "2021"

[dependencies]
mcl_rust = { path = '../kzg' }
# TODO: Use `std` feature once https://github.com/supranational/blst/pull/150 or similar upstreamed
blst = { git = 'https://github.com/subspace/blst.git', rev = "017edf9d7b943813b9ba2804a9eda20607b48139" }
kzg = { path = "../../kzg" }
kzg-bench = { path = "../../kzg-bench" }

[dev-dependencies]
rand = "0.8.5"
criterion = "0.4.0"

[features]
minimal-spec = ["kzg/minimal-spec", "kzg-bench/minimal-spec"]

[[bench]]
name = "shared_fk20"
harness = false

[[bench]]
name = "shared_zero_poly"
harness = false

[[bench]]
name = "shared_fft"
harness = false

[[bench]]
name = "shared_poly"
harness = false

[[bench]]
name = "shared_das"
harness = false

[[bench]]
name = "shared_recover"
harness = false

[[bench]]
name = "shared_kzg_proof"
harness = false

[[bench]]
name = "shared_eip_4844"
harness = false

[[bench]]
name = "shared_lincomb"
harness = false
