name: blst-from-scratch benchmarks

on: [push, pull_request, workflow_dispatch]

env:
  C_KZG_4844_GIT_HASH: 'fd24cf8e1e2f09a96b4e62a595b4e49f046ce6cf'

jobs:
  benchmarks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-11]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.19

      - name: "[blst-from-scratch] Benchmark"
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --manifest-path blst-from-scratch/Cargo.toml

      - name: "[blst-from-scratch] Benchmark (parallel)"
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --manifest-path blst-from-scratch/Cargo.toml --features parallel

      - name: "[blst-from-scratch] Benchmark (c-kzg-4844)"
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd blst-from-scratch && bash run-c-kzg-4844-benches.sh

      - name: "[blst-from-scratch] Benchmark (c-kzg-4844 parallel)"
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd blst-from-scratch && bash run-c-kzg-4844-benches.sh --parallel
